---
name: build
on: [push, pull_request]
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp_vsn: ['24', '25', '26']
        rebar3_vsn: ['3.22']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: ${{matrix.rebar3_vsn}}
      - name: Format check
        run: rebar3 format --verify
      - run: rebar3 test
      - name: test our example
        run: |
          cd example
          rebar3 release
          _build/default/rel/example/bin/example daemon
          _build/default/rel/example/bin/example ping
      - name: Format check
        run: |
          cd example
          rebar3 format --verify
      - name: check our example
        run: |
          cd example
          rebar3 test
